### PR TITLE
Update parameters to 'before rescaling' ones

### PR DESCRIPTION
**Pull request by ryo-ARAKI**

### CODE REVIEW

**Comment by ryo-ARAKI** [comment]
@T-Tanogami I would like to set parameters to the "guessed" stage in the paper, as you described in https://github.com/ryo-ARAKI/Sabra_shell_model/issues/24#issuecomment-955144038, but I am not certain with the Reyonlds number. Do you have any suggestions?

**Comment by T-Tanogami** [comment]
@ryo-ARAKI Since the Reynolds number is given by
Re := u_rms / (1 × k_M), (\nu = 1)
it is independent of the scaling with \epsilon, i.e., 
Re --> (u_rms/\epsilon^{1/4}) / (1 × k_M/\epsilon^{1/4}) = u_rms / (1 × k_M) = Re.

So, the following parameter values, 
\theta_K = 2.83 × 10^-8
Re = 2.04 × 10^6
k_0 = 1
f_M, f_M+1 given by Eq. (IV.2)
should reproduce u_rms = 56.48 and \epsilon = 1.478.

**Comment by ryo-ARAKI** [comment]
@T-Tanogami OK, I update Re accordingly. 
I have been implementing the "restart computation" function in a different pull request https://github.com/ryo-ARAKI/Sabra_shell_model/pull/36 (, but not validated the implementation yet). Once it is done, we can conduct as long a computation as we want :+1:

**Review by T-Tanogami — APPROVED** [review]
OK

BTW, is "e6" the same as "e+6"?

**Comment by ryo-ARAKI** [comment]
@T-Tanogami Yes, both mean "ten to the power of 6".

```Julia
julia> using Printf

julia> a = 1e6
1.0e6

julia> println(@sprintf "%f" a)
1000000.000000
```

**Pull request merged**
