### PR TITLE
Add `flag_restart` to handle restart of computation

### PR DESCRIPTION
**Pull request by ryo-ARAKI**
Close the issue https://github.com/ryo-ARAKI/Sabra_shell_model/issues/35

### CODE REVIEW

**Comment by ryo-ARAKI** [comment]
To Do: check whether the restarted computations lead to the same result as the long computation.
To check this, we need to fix the seed of random variables.

**Comment by ryo-ARAKI** [comment]
n=-15_07_thetaK=2 328e-08_Re=2 040e+06

I save the intermediate field at itr=5E4 to compare itr=6E4 of the original/restarted computations.
Here, the two spectra collapse well up to k \approx 5, but there is a large discrepancy in the dissipation range.

**Comment by ryo-ARAKI** [comment]
Data at itr=6E4 is the following (wavenumber, original, restarted)

```dat

3.1e-05 9.61915e-01	9.61915e-01
6.1e-05 1.07473e+00	1.07473e+00
1.2e-04 5.34133e-01	5.34133e-01
2.4e-04 9.94230e-01	9.94230e-01
4.9e-04 9.47399e-01	9.47399e-01
9.8e-04 2.41292e-01	2.41292e-01
2.0e-03 7.89466e-01	7.89466e-01
3.9e-03 1.29816e+00	1.29816e+00
7.8e-03 1.06206e+00	1.06206e+00
1.6e-02 7.94269e-01	7.94271e-01
3.1e-02 5.75100e-01	5.75101e-01
6.2e-02 3.01372e-01	3.01369e-01
1.2e-01 9.57787e-01	9.57783e-01
2.5e-01 4.70665e-01	4.70679e-01
5.0e-01 6.46356e-01	6.46249e-01
1.0e+00 5.58636e-01	5.58500e-01
2.0e+00 6.68789e-02	6.66679e-02
4.0e+00 3.60538e-03	3.77338e-03
8.0e+00 4.97027e-04	1.55604e-04
1.6e+01 2.13011e-04	1.22272e-04
3.2e+01 2.22939e-04	1.65507e-04
6.4e+01 3.07545e-04	2.48972e-04
1.3e+02 1.08836e-04	3.02519e-04
```

**Review by T-Tanogami — APPROVED** [review]
I understand the code and checked that it works well.

**Pull request merged**
